First Alura Class on NLP

(Processamento de linguagem natural na análise de sentimentos)

1. Importing Necessary Libraries

In [24]:
import pandas as pd
import sklearn as sk

2. Loading dataframes

In [13]:
df = pd.read_csv('https://raw.githubusercontent.com/vqrca/nlp_analise_sentimento/refs/heads/main/Dados/dataset_avaliacoes.csv')

In [14]:
df.head()

,ID_avaliacao,avaliacao,nota,sentimento
0,81841,"Esse smartphone superou minhas expectativas, r...",5,positivo
1,28031,o cheiro e muito desagradavel!! pra quem se in...,2,negativo
2,91332,"Eu fiz a compra a loja não entregou o produto,...",1,negativo
3,110045,"Atendeu minhas expectativas, só achei a luz ru...",4,positivo
4,36929,"Gostei muito, só achei que ficou a desejar a q...",5,positivo

In [15]:
df.shape

(15501, 4)

In [16]:
df.value_counts('sentimento')

sentimento
positivo    7890
negativo    7611
Name: count, dtype: int64

In [11]:
print('Positiva \n')

df.avaliacao[0]

Positiva

'Esse smartphone superou minhas expectativas, recomendo'

In [12]:
print('Negativa \n')

df.avaliacao[2]

Negativa

'Eu fiz a compra a loja não entregou o produto, a compra foi feita no cartão de credito e ate o momento a loja também nao me devolveu o valor da compra.'

3. Transformando os dados textuados em dados númerios utilizando a técnica "Bag of Words" 
Tal tecnica consiste em quantificar a frequencia de cada uma das palavras do texto inputado. 
Dessa forma é possivel verificar a frequencia de cada palavra. O resultado disso é um vertor que detalha tal frequencia.

In [2]:
from sklearn.feature_extraction.text import CountVectorizer 

texto = ['comprei um produto ótimo', 'comprei um produto ruim']

vetorizar = CountVectorizer()

bag_of_words = vetorizar.fit_transform(texto)

In [3]:
bag_of_words

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (2, 5)>

4. Usando pandas para vizualiar o resultado da transformação feita pela função countVectorizer

In [9]:
matriz_esparsa = pd.DataFrame.sparse.from_spmatrix(bag_of_words, columns=vetorizar.get_feature_names_out())

In [10]:
matriz_esparsa

   comprei  produto  ruim  um  ótimo
0        1        1     0   1      1
1        1        1     1   1      0

5. Agora é vamos fazer o processo de vetorização no dataframe que começamos a trabalhar. 
Também é possivel ver a quantidade de dados que esta vetorização irá gerar com o .shape

In [17]:
vetorizar = CountVectorizer(lowercase=False)
bag_of_words = vetorizar.fit_transform(df.avaliacao)
print(bag_of_words.shape)

(15501, 23352)

6. Visto que o resultado da vetorização do data frame é muito extensa, é ideal que o resultado seja limitado para que diminua o custo computacional desse experimento. (max_features - limita o número de colunas. No contexto deste experimento, isso significa que somente as 50 palavras mais frequentes dentro do DF serão mostradas)

In [18]:
vetorizar = CountVectorizer(lowercase=False, max_features=50)
bag_of_words = vetorizar.fit_transform(df.avaliacao)
print(bag_of_words.shape)

(15501, 50)

In [20]:
matriz_esparsa_avaliacores = pd.DataFrame.sparse.from_spmatrix(bag_of_words, columns=vetorizar.get_feature_names_out())
matriz_esparsa_avaliacores

,Não,Produto,ainda,antes,as,até,bem,bom,chegou,com,...,qualidade,que,recebi,recomendo,se,sem,tem,um,uma,veio
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,1,0,0,0,...,1,2,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15496,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
15497,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,1,0,0,0
15498,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
15499,0,1,0,1,0,0,0,1,1,0,...,0,0,0,0,0,0,0,0,0,0
15500,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

7. No entanto, a simplicidade também traz limitações: como o Bag of Words não considera a ordem das palavras, ele pode ignorar aspectos importantes do contexto e do significado do texto.

8. Agora é possível iniciar a criação do modelo. Primeiramente é necessário separar os dados, definindo uma parte dos mesmos para treino

In [25]:
from sklearn import train_test_split

ImportError: cannot import name 'train_test_split' from 'sklearn' (c:\Users\vimph\OneDrive\Documentos\Projects\NLP\.venv\Lib\site-packages\sklearn\__init__.py)